In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [12]:
dataset = pd.read_csv('DataPreprocessing.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [13]:
print(x)

[['France' 45.0 75000.0]
 ['Spain' 28.0 39000.0]
 ['Germany' 47.0 76000.0]
 ['Spain' nan 61000.0]
 ['Germany' 40.0 62000.0]
 ['France' 38.0 60000.0]
 ['Spain' 32.0 50000.0]
 ['France' 48.0 nan]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]
 ['Germany' 49.0 79000.0]
 ['Spain' 33.0 55000.0]
 ['France' 42.0 72000.0]
 ['Spain' 25.0 28000.0]
 ['Germany' nan nan]]


In [14]:
print(y)

['No' 'Yes' 'Yes' 'No' 'Yes' 'Yes' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No'
 'Yes' 'Yes']


In [16]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [17]:
print(x)

[['France' 45.0 75000.0]
 ['Spain' 28.0 39000.0]
 ['Germany' 47.0 76000.0]
 ['Spain' 39.53846153846154 61000.0]
 ['Germany' 40.0 62000.0]
 ['France' 38.0 60000.0]
 ['Spain' 32.0 50000.0]
 ['France' 48.0 62076.92307692308]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]
 ['Germany' 49.0 79000.0]
 ['Spain' 33.0 55000.0]
 ['France' 42.0 72000.0]
 ['Spain' 25.0 28000.0]
 ['Germany' 39.53846153846154 62076.92307692308]]


In [ ]:
print(y)

In [22]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [23]:
print(x)

[[1.0 0.0 0.0 45.0 75000.0]
 [0.0 0.0 1.0 28.0 39000.0]
 [0.0 1.0 0.0 47.0 76000.0]
 [0.0 0.0 1.0 39.53846153846154 61000.0]
 [0.0 1.0 0.0 40.0 62000.0]
 [1.0 0.0 0.0 38.0 60000.0]
 [0.0 0.0 1.0 32.0 50000.0]
 [1.0 0.0 0.0 48.0 62076.92307692308]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]
 [0.0 1.0 0.0 49.0 79000.0]
 [0.0 0.0 1.0 33.0 55000.0]
 [1.0 0.0 0.0 42.0 72000.0]
 [0.0 0.0 1.0 25.0 28000.0]
 [0.0 1.0 0.0 39.53846153846154 62076.92307692308]]


In [24]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [25]:
print(y)

[0 1 1 0 1 1 1 1 0 1 0 1 0 1 1]


In [26]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [27]:
print(x_train)

[[0.0 1.0 0.0 47.0 76000.0]
 [0.0 1.0 0.0 49.0 79000.0]
 [0.0 1.0 0.0 40.0 62000.0]
 [0.0 0.0 1.0 28.0 39000.0]
 [0.0 0.0 1.0 25.0 28000.0]
 [1.0 0.0 0.0 45.0 75000.0]
 [0.0 1.0 0.0 39.53846153846154 62076.92307692308]
 [1.0 0.0 0.0 37.0 67000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 42.0 72000.0]
 [0.0 0.0 1.0 33.0 55000.0]
 [1.0 0.0 0.0 38.0 60000.0]]


In [28]:
print(x_test)

[[0.0 0.0 1.0 39.53846153846154 61000.0]
 [1.0 0.0 0.0 48.0 62076.92307692308]
 [0.0 0.0 1.0 32.0 50000.0]]


In [29]:
print(y_train)

[1 0 1 1 1 0 1 1 0 0 1 1]


In [31]:
print(y_test)

[0 1 1]


In [33]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [34]:
print(x_train)

[[0.0 1.0 0.0 0.9965042553917187 0.8192741139454632]
 [0.0 1.0 0.0 1.260882935393603 1.0108884494409538]
 [0.0 1.0 0.0 0.07117887538512296 -0.07492611836682589]
 [0.0 0.0 1.0 -1.515093204626184 -1.5439693571655866]
 [0.0 0.0 1.0 -1.9116612246290108 -2.246555253982385]
 [1.0 0.0 0.0 0.7321255753898341 0.7554026687802997]
 [0.0 1.0 0.0 0.010168410769303683 -0.07001293027719785]
 [1.0 0.0 0.0 -0.32538914461770374 0.24443110745899163]
 [0.0 1.0 0.0 1.3930722753945455 1.2663742301016077]
 [1.0 0.0 0.0 0.33555755538700743 0.5637883332848092]
 [0.0 0.0 1.0 -0.8541465046214728 -0.5220262345229704]
 [1.0 0.0 0.0 -0.19319980461676153 -0.2026690086971529]]


In [35]:
print(x_test)

[[0.0 0.0 1.0 0.010168410769303683 -0.13879756353198938]
 [1.0 0.0 0.0 1.128693595392661 -0.07001293027719785]
 [0.0 0.0 1.0 -0.986335844622415 -0.841383460348788]]
